### ISSUE TITLE
MessageSubscription: Breaking change from 5.1 to 5.2?

### ISSUE THREAD

**Issue by Tarostar** [commercetools/commercetools-dotnet-core-sdk-v2#201]
Is there a breaking change in the MessageSubscription class (commercetools.Sdk.Api.Models.Subscriptions), or have we have been using ResourceTypeId wrong?

SDK-V2 v.5.1.1
```
public class MessageSubscription : IMessageSubscription
{
  public string ResourceTypeId { get; set; }
  public List<string> Types { get; set; }
}
```

SDK-V2 v.5.2.0
```
public interface IMessageSubscription
{
  IMessageSubscriptionResourceTypeId ResourceTypeId { get; set; }
  List<string> Types { get; set; }
}
```

We create new MessageSubscriptions like this:
```
new MessageSubscription
{
    ResourceTypeId = ReferenceTypeId.Order.GetDescription(),
    Types = new List<string>
    {
        new OrderStateTransitionMessage().Type,
    }
}
```

Now we have to update all of them to this:
```
new MessageSubscription
{
    ResourceTypeId = IMessageSubscriptionResourceTypeId.Order,
    Types = new List<string>
    {
        new OrderStateTransitionMessage().Type,
    }
}
```

Same is also true for ChangeSubscription.

**Comment by jenschude** [comment]
Uh yeah.

We didn't catched the change of the type from String to IMessageSubscriptionResourceTypeId. Also the impact may be not that high as the Enum interfaces also implement IEnumerable<char> so that they are comparable to a string.

For future releases with automated detection of the changes we now get a more complete view of the generated parts and can prevent this.

Sorry for the inconvenience.
